name: Queue Handlers Deploy

on:
  workflow_run:
    workflows: [Queue Handlers Check]
    types: [completed]
    branches: [staing, production]

jobs:
  release:
    strategy:
    matrix:
      folder:
        - queue-handler
        - webhook-queue-handler
        - telegram-queue-handler

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

      - name: Build lambda
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-06-20
          override: true
          profile: minimal
      - name: Use cargo-lambda
        run: |
          cargo install cargo-lambda

      - name: Build release lambda
        run: |
          cargo lambda build --release
