name: Queue Handlers Deploy

on:
  push:
    branches: [ staging, production, main ]
  pull_request:
    branches: [ staging, production, main ]
# on:
#   workflow_run:
#     workflows: [Queue Handlers Check]
#     types: [completed]
#     branches: [staging, production]

jobs:
  release:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [ queue-handler ]

    steps:

      - name: Build lambda
        uses: actions/checkout@v2

      - name: Uses zig # cargo-lambda dependency
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-06-20
          override: true
          profile: minimal
          
      - name: Install cargo-lambda
        uses: actions-rs/install@v0.1
          with:
            crate: cargo-lambda
            version: latest

      - name: Build release lambda
        run: |
          cd ${{ matrix.folder }}
          cargo lambda build --release

      - name: Deploy to AWS Lambda
        run: |
          echo "Implement me"
